### PR TITLE
Modernize the package a bit

### PR DESCRIPTION
**Pull request by strugee**
See the individual commit messages for what's been done, any description here would just pretty much be repeating that list :-)

### CODE REVIEW

**Comment by dominicbarnes** [comment]
I'm not maintaining this package anymore, feel free to fork it if you wish to make changes to it.

**Comment by strugee** [comment]
OK, good to know, thanks!

I don't suppose you'd want to just transfer ownership to me? If that makes you nervous though (thinking about e.g. the event-stream security incident here) I can just publish as a fork.

**Comment by dominicbarnes** [comment]
I'd like to keep the original repo, but I'll happily hand over the npm package so you can publish to that for future versions.

**Comment by strugee** [comment]
Wonderful, that would be great. I'm strugee on npm as well.

I actually didn't mean to say transfer ownership and I'm not sure why I did - what I _should_ have suggested is you giving me collaborator access to your repo. Otherwise I'd be happy to just use my fork, whatever works best for you is fine :thumbsup:

**Comment by dominicbarnes** [comment]
@strugee I've just added you as a maintainer for this [npm package](https://www.npmjs.com/package/minecraft-server-properties)

I'll close out this ticket, feel free to comment more if you need anything else from me though.

**Comment by strugee** [comment]
@dominicbarnes I kinda forgot about this but I just published 1.0.0 to npm with some cleanups. Not sure if you want to add a link anywhere (GitHub description maybe?) noting that PRs/issues/whatever should be sent to https://github.com/strugee/node-minecraft-server-properties

**Pull request closed without merging**
